apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: anikhilt/gke-flask-app/service2:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service2-service
spec:
  selector:
    app: service2
  ports:
    - protocol: TCP
      port: 81
      targetPort: 5000
  type: LoadBalancer
