version: '3'
services:
  service1:
    image: anikhilt/service1:latest
    ports:
      - "8081:8080"

  service2:
    image: anikhilt/service2:latest
    ports:
      - "8082:8080"

  service3:
    image: anikhilt/service3:latest
    ports:
      - "8083:8080"

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
      - service3
