apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service3
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
      - name: service3
        image: anikhilt/gke-flask-app/service3:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service3-service
spec:
  selector:
    app: service3
  ports:
    - protocol: TCP
      port: 82
      targetPort: 8080
  type: LoadBalancer
